### ISSUE TITLE
2-scripted-Jenkinsfile.groovy error in conversion

### ISSUE THREAD

**Issue by jkzilla** [heug/jenkinsfile-circleci#14]
**Describe the bug**
node index.js test/configs/jenkinsfile-examples/nodejs-build-test-deploy-docker-notify/2-scripted-Jenkinsfile.groovy

throws 

TypeError: Cannot read property 'pipeline' of undefined
    at map (/Users/johannag/src/jenkinsfile-circleci/mapping/mapper.js:17:23)
    at /Users/johannag/src/jenkinsfile-circleci/index.js:66:30
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
Error in conversion

**Comment by jkzilla** [comment]
johannag@Johannas-MacBook-Pro jenkinsfile-circleci % node index.js test/configs/jenkinsfile-examples/msbuild/Jenkinsfile
TypeError: Cannot read property 'pipeline' of undefined
    at map (/Users/johannag/src/jenkinsfile-circleci/mapping/mapper.js:17:23)
    at /Users/johannag/src/jenkinsfile-circleci/index.js:66:30
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
Error in conversion

vs 

jenkinsfile-circleci % node index.js test/configs/declarative-examples/jenkinsfile-examples/mavenDocker.groovy
version: 2.1
jobs:
  Build:
    steps:
      - comment: |-
          Translation of non-literal commands are not currently supported by this tool
          withMaven ${[findbugsPublisher(), junitPublisher(ignoreAttachments: false)]}
  Integration Test:
    steps:
      -
        run: 'mvn sonar:sonar -Dsonar.login=$SONAR_PSW'
  Sonar Scan:
    steps:
      -
        run: 'mvn sonar:sonar -Dsonar.login=$SONAR_PSW'
  Build and Publish Image:
    steps:
      - comment: |-
          Translation of non-literal commands are not currently supported by this tool
          sh """
                    docker build -t ${IMAGE} .
                    docker tag ${IMAGE} ${IMAGE}:${VERSION}
                    docker push ${IMAGE}:${VERSION}
                  """
workflows:
  version: 2
  build-and-test:
    jobs:
      - Build: {}
      - Integration Test:
          requires:
            - Build
      - Sonar Scan:
          requires:
            - Build
      - Build and Publish Image:
          requires:
            - Sonar Scan

**Comment by makotom** [comment]
Thanks for your report, @jkzilla !

Looks like both of the two examples are Scripted Pipelines, which are currently out of our scope (currently we are focusing only on Declarative Pipelines).
Due to this nature, the background converter is failing to parse those Jenkinsfiles.

@heug Can you categorize which Jenkinsfiles in the `test` directory are in our scope and which are not, and label them concisely (e.g. move those out of scope to "unsupported" directory)? I can easily imagine that it is too complicated for first-time visitors to distinguish them - even I am sometimes confused. 😇
